### ISSUE TITLE
[Feature Request] Add support to NextCloud (or other synchronised service) files access

### ISSUE THREAD

**Issue by b3** [SimpleMobileTools/Simple-File-Manager#377] opened 2020-01-28 09:01 UTC
It would be very nice to be able to browse files synchronized with [Nextcloud](https://nextcloud.com/install/#install-clients) (or other such services) on the phone (aka having `Internal`, `SD Card`, `Root` plus `Nextcloud`).

Under LineageOS (and derived OS, such as /e/ for instance) it seems that that is possible not only with the file manager but also with any file chooser used by apps.

IMHO, being able to use such synchronized file system in all your apps, would be a real advantage on a mobile phone at different levels (backup, ease of configuration, etc.).

I imagine that means using some different library offered by the android stack (maybe the one called *Storage Access Framework*) and as I am a total Android dev ignorant I am not able to measure the amount of work that will ask.

**Comment by seniorm0ment** [comment] 2022-09-08 16:12
Would really love to see this! Sucks needing to use different apps.
Would also love to be able to view photos in SimpleGallery.

**Comment by abmurksi** [comment] 2022-11-22 13:04
Isn't this a duplicate of Issue #539 (or vice versa)

**Closed** 2022-11-22 15:07 UTC
Labels: feature request
