### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [SimpleMobileTools/Simple-File-Manager#42] opened 2016-12-10 18:59 UTC
When I perform this sequence of events, the dialog on screen disappears:

Sequence 1:
1. Click on Add item
2. Orientation change

Sequence 2:
1. Long click on file
2. Click on Edit
3. Orientation change

Sequence 3:
1. Long click on file
2. Open Overflow Menu
3. Click on Delete
4. Orientation change

Sequence 4:
1. Long click on file
2. Open Overflow Menu
3. Click on Copy/Move
4. Orientation change

Sequence 5:
1. Long click on file
2. Open Overflow Menu
3. Click on Copy/Move
4. Click on Select Destination
5. Orientation change

Sequence 6:
1. Long click on file
2. Click on Properties
3. Orientation Change

**Comment by trubitsyn** [comment] 2017-11-05 21:02
@tibbi could not reproduce any of them. Seems like that's fixed now in Commons.

**Comment by tibbi** [comment] 2017-11-05 21:08
i wasnt optimizing anything related to rotating devices intentionally, so guess I somehow fixed it by mistake :p closing it anyway, thanks

**Closed by tibbi** 2017-11-05 21:08 UTC
Labels: bug
