### ISSUE TITLE
Use root access to explore android/data and android/obb

### ISSUE THREAD

**Issue by BioRider17** [SimpleMobileTools/Simple-File-Manager#724] opened 2023-07-15 21:47 UTC
Since android 11 removed the "use this folder" workaround, I think it's a good Idea to use root access for those folders on 11 and up.

**Comment by Aga-C** [comment] 2023-07-16 04:35
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/724.

**Comment by Aga-C** [comment] 2023-07-16 04:36
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/685.

**Closed** 2023-07-16 04:37 UTC
