### ISSUE TITLE
why the app doesn't use MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [SimpleMobileTools/Simple-File-Manager#505] opened 2021-10-05 06:31 UTC
It can't read Android/data because it doesn't use the new MANAGE_EXTERNAL_STORAGE permission. Why you don't use it instead of READ_EXTERNAL_STORAGE?

**Comment by tibbi** [comment] 2021-10-05 06:39
the new way of handling /Android/data is more complicated, it is not just some permission. Duplicate of #490

**Closed by tibbi** 2021-10-05 06:39 UTC
