### ISSUE TITLE
Can't rename files on external SD card

### ISSUE THREAD

**Issue by Plut0nio** [SimpleMobileTools/Simple-File-Manager#547] opened 2022-01-11 18:02 UTC
I recently replaced my Galaxy A52 5G's 128 GB microSD card with a 512 GB one. I transferred all the data from the 128 GB one to the 512 GB one using a Windows PC before putting the latter into my phone. It seems to be working fine now, except for the fact that I can no longer rename files that are on the SD card using either Simple File Manager or Simple Gallery Pro (Im using versions 6.11.3 and 6.22.3 from F-Droid, respectively). Whenever I try to do so, I get a gray pop-up message on the bottom of the screen saying "An error occurred: java.lang.NullPointerException: authority" followed shortly by another pop-up saying "An unknown error occurred". For files on internal storage, I can rename them just fine without issue. Samsung's stock file browser (My Files) also has no issue renaming files on either internal storage or the SD card. Sorry if this isn't an issue on Simple Tools' side, I'm just pretty stumped. Thanks.

**Comment by tibbi** [comment] 2022-02-05 11:34
what OS version are you using?

**Comment by Aga-C** [comment] 2022-02-05 13:15
@tibbi This issue is reproducible on an emulator.

**Comment by Plut0nio** [comment] 2022-02-05 14:42
> what OS version are you using?

Android 11

![Screenshot_20220205-094116_Settings.jpg](https://user-images.githubusercontent.com/24761328/152646452-0a1d310b-a2c6-47b9-a1cc-3a9e336cd58c.jpg)

**Comment by tibbi** [comment] 2022-02-09 21:55
@Aga-C I cannot reproduce it on an emulator, can you still do it with the latest app version?

**Comment by tibbi** [comment] 2022-02-09 22:01
actually, if I checkout some older code I get that error too. So guess it is fixed now.

**Closed by tibbi** 2022-02-09 22:01 UTC
Labels: bug

**Comment by Aga-C** [comment] 2022-02-09 22:30
Yes, it works now.

**Comment by Plut0nio** [comment] 2022-02-10 16:41
I installed the newest File Manager (6.11.4) and it works. 👍

I'm assuming this fix will also be applied to the next release of Simple Gallery? It has the same issue. Thanks!
