### ISSUE TITLE
UX improvement (Delete, Move, Copy, Share buttons) location on Bottom instead of top

### ISSUE THREAD

**Issue by decodering22** [SimpleMobileTools/Simple-File-Manager#463] opened 2021-04-15 18:17 UTC
I really want to replace the default samsung file manager like i have with Simple Gallary Pro, but there is a few thing preventing me.

User ability UX and ergonomics - On these large phone it is much easier having a these buttons at the bottom. Samsung My Files pops up "Move, Copy, Share and Delete" menu (Frankly the new Myfiles has "More" and it's not needed). It is much faster and easier to select the option you want than having to take your hand off the phone or reposition it to reach to the top of the phone to delete these files right now. 

![Screenshot_20210415-093421_My Files](https://user-images.githubusercontent.com/78891534/114918356-d745b300-9ddb-11eb-8029-5b85745f6f3e.jpg)

**Comment by decodering22** [comment] 2021-04-15 18:23
Will be glad to help test and debug like I have for other open source projects.

**Comment by tibbi** [comment] 2021-04-16 19:46
duplicate of #316

**Closed by tibbi** 2021-04-16 19:46 UTC
