### ISSUE TITLE
More control over font size and colors

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/Simple-File-Manager#124] opened 2017-11-07 22:31 UTC
Feature request: this one is perhaps in the category 'not really necessary', but for some of us it would be great if the font size of the folders/files could be managed in some way; a 'large - normal - small' font option would already be great in the 'Customize colors' page. And when you're working in that area, it also would be nice to have control over the folder colors, e.g. to use that shiny orange color for folders instead of that dull gray :-)

**Comment by tibbi** [comment] 2018-04-15 20:15
colors are a duplicate of #46 , I dont really plan adding folder coloring. Thanks

**Closed by tibbi** 2018-04-15 20:15 UTC
Labels: feature request
