### ISSUE TITLE
no pdf file preview

### ISSUE THREAD

**Issue by dikasetyaprayogi** [SimpleMobileTools/Simple-File-Manager#686] opened 2023-02-14 13:44 UTC
i recall this is solved in #180 . but the latest 6.15.2 version cant thumbnail pdf, is this a bug ?

**Comment by tibbi** [comment] 2023-02-14 17:32
what folders does it happen to?

**Comment by Aga-C** [comment] 2023-02-14 20:56
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/464.

**Closed** 2023-02-14 21:46 UTC
