### ISSUE TITLE
More View types

### ISSUE THREAD

**Issue by smarquespt** [SimpleMobileTools/Simple-File-Manager#33] opened 2016-11-21 21:45 UTC
Now we only have list view. I suggest you to add some more view types like:

Columns
Grid
Detailed list

**Comment by ascuccaro** [comment] 2016-12-22 14:13
I completely agree with this. The grid view becomes specially useful in picture folders. And detailed view helps a lot when looking up size and date differences quickly without having to go and open up the properties of each file one by one. Not sure what would be column view, though, heh.

**Comment by tibbi** [comment] 2022-07-31 16:19
duplicate of #563

**Closed by tibbi** 2022-07-31 16:19 UTC
Labels: feature request
