### ISSUE TITLE
Refresh icon behave strangely

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#340] opened 2019-08-06 07:39 UTC
## steps to reproduce
On a not rooted device

1. Open the app
2. Select the first item (folder) in the list
3. Enter the select mode, the first item is selected. The refresh icon appears and is frozen on the screen.

<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/62521060-7b363780-b861-11e9-9d5f-9037c34f605a.png" width="50%" height="50%">
</div>

## expected result

* refresh icon disappear after refreshed.

## observed behavior

* refresh icon **did not** disappear after refreshed.

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v 6.3.3 from Google Play

**Comment by tibbi** [comment] 2019-08-06 07:47
what exactly is strange?

**Comment by arthur-star** [comment] 2019-08-06 07:48
Updated

**Comment by tibbi** [comment] 2019-08-06 07:49
duplicate of #175

**Closed by tibbi** 2019-08-06 07:49 UTC
