### ISSUE TITLE
Feature request: recycle bin

### ISSUE THREAD

**Issue by Pauler221** [SimpleMobileTools/Simple-File-Manager#487] opened 2021-06-06 18:32 UTC
Hello, first of all thx for the great app! 

It’d be really nice to have a recycle bin option within your file manager in case you accidentally delete a file or is it just me who cannot find it? 

Greetings

**Comment by tibbi** [comment] 2021-06-07 06:21
duplicate of #66

**Closed by tibbi** 2021-06-07 06:21 UTC
