### ISSUE TITLE
[feature request] Add access to remote webdav folder

### ISSUE THREAD

**Issue by tusch001** [SimpleMobileTools/Simple-File-Manager#324] opened 2019-06-09 05:50 UTC
Remote storage is becoming more and more popular. People using your file manager are most likely the same people hosting remote files on their own cloud, e.g. nextcloud, owncloud, ... due to privacy reasons. I would love to have an easy way to copy files to a remote folder with either  webdav protocol (or / and SMB2 or sftp). All in one app. Maybe with support for different logins / accounts for private and business.

I used ES file explorer for that (old version 3.2.5.5 before it was sold to spying China) because it made copying files so easy. Is there any hope that you implement such network functionality in the file manager?

Thx

Patricia

**Comment by tibbi** [comment] 2019-06-09 06:53
not sure if it wont require some internet related permission. If it will, it definitely wont be added.

**Comment by tusch001** [comment] 2019-06-12 14:21
@webdav-protocol
My passwort manager (safeincloud) stores a copy of the vault in my nextcloud. It never asked for internet permission since it is using the same method as a browser (for webdav). And simple internet access is never asked for, it's google business model. Otherwise you could block all apps / all advertisement :-). If the user has a firewall he must allow internet access for your app as a trade off.
I just tested it by re-installing the password manager app (screenshot below). It is obviously able to read directories and even to create folders and files. That's all I need for backing up files. In this app the login credentials are stored in the app (hopefully encrypted) but I think you could use android accounts for that. The nextcloud bookmark (org.schabi.nxbookmarks) app uses the account system if you want to have a look there how to implement it. If you don't want to ask for any permissions then encrypt the login / passwort and store it in the app.

I'm not a developer but I know a little bit about the webdav backend in nextcloud from years ago when implementation was very buggy. You more or less ask for a webpage with a certain path that includes folder(s) and filename and provide credentials. Actions on files are added to the path. The webserver sends you back the webpage with a list of folders / files which needs to be parsed or the result of the action. This should be manageable (there is also the nextloud app to copy the idea).

@Smb2 / windows network: no idea how that is done. There are not many apps which can do it and they are crappy file explorers. Don't know about permissions. And from setting up the LANdrive app (fr.webrox.landrive) I know that there are issues with port compatibility (non rooted android only > 1024, windows without port forwarder only < 1024. So not easy and only in rooted phones manageable. So much for not asking for any permissions :-(

Summary:
I think webdav protocol without permissions. Thanks for even considering the idea.

Patricia

![Screenshot_Paket-Installer-SafeInCloud](https://user-images.githubusercontent.com/46721195/59358182-655a3980-8d2c-11e9-9425-2bbc3814906b.png)

**Comment by aguaviva** [comment] 2021-12-20 00:11
This can be done using SAF

**Comment by tibbi** [comment] 2023-07-26 21:10
duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/539

**Closed by tibbi** 2023-07-26 21:10 UTC
Labels: feature request

**Comment by rokejulianlockhart** [comment] 2023-07-26 22:33
@tibbi, shouldn't this be closed as invalid if it's a duplicate? Also, this request seems to track native support rather than the ability to add a provider's URI to SFM.
