### ISSUE TITLE
[Feature request] Display size/free storage space

### ISSUE THREAD

**Issue by DuMuT6p** [SimpleMobileTools/Simple-File-Manager#451] opened 2021-02-21 12:43 UTC
Hello,
It could be good to have the size/free space remaining on the whole root file system or SD card. Currently the size of folders is displayed on their info, but I couldn't find for the whole storage space.

**Comment by tibbi** [comment] 2021-02-21 15:14
duplicate of #123

**Closed by tibbi** 2021-02-21 15:14 UTC
