### ISSUE TITLE
Cannot enter any folders in root, Android 11

### ISSUE THREAD

**Issue by ioogithub** [SimpleMobileTools/Simple-File-Manager#491] opened 2021-06-29 02:53 UTC
Although I have root enabled in the settings. I can display the folder list in root but tapping on any folder does nothing. Root does not appear to be working.

**Comment by tibbi** [comment] 2021-06-29 06:21
what app version are you using?

**Comment by ioogithub** [comment] 2021-06-29 18:38
Version 6.20.1 from F-Droid

**Comment by tibbi** [comment] 2021-06-29 21:02
You sure it is the File Managers version? Sounds like the version of your gallery.

**Comment by ioogithub** [comment] 2021-06-29 21:31
Sorry you are correct the version is 6.9.2 from F-Droid. Is the problem because you are targeting SDK29?

I have a few other file managers that seem to be able to navigate root however I really like you suite of apps.

I am on Android 11 (LineageOS 18.1) on Lenovo Z6 Pro

**Comment by tibbi** [comment] 2021-06-30 06:29
I dont know, Android 11 seems to have changed quite a few things.

**Comment by tibbi** [comment] 2021-07-29 10:15
duplicate of #490

**Closed by tibbi** 2021-07-29 10:15 UTC
