### ISSUE TITLE
Add support rar

### ISSUE THREAD

**Issue by Stu75e** [SimpleMobileTools/Simple-File-Manager#728] opened 2023-07-22 07:39 UTC
Please include the ability to open rar files as well

**Comment by Aga-C** [comment] 2023-07-22 08:03
It's a.duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/93.

**Comment by Aga-C** [comment] 2023-07-22 08:04
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/93.

**Closed** 2023-07-22 21:28 UTC
