### ISSUE TITLE
feature request: disabling thumbnails preview

### ISSUE THREAD

**Issue by unofficial-hima** [SimpleMobileTools/Simple-File-Manager#701] opened 2023-04-20 08:15 UTC
I find this feature in total commander, and it makes it a lot faster
I would like to see it in here, please
thanks

**Comment by Aga-C** [comment] 2023-04-20 08:35
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/572.

**Closed** 2023-04-20 10:43 UTC
