### ISSUE TITLE
Can't open password protecfed 7z file

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [SimpleMobileTools/Simple-File-Manager#364] opened 2019-11-12 19:29 UTC
Title. It's password protected, .7z and no option to extract

**Comment by tibbi** [comment] 2019-11-12 19:58
duplicate of #189

**Closed by tibbi** 2019-11-12 19:58 UTC

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-13 04:16
Oops! My bad!!
